### PR TITLE
Bugfix/adding correct namespacing

### PR DESCRIPTION
**Pull request by cgsmith**
Hey @solverat can you take a peak? I put back all of the proper namespaces. 

Does this address the issue? I branched from `master` for this bugfix so it has your classes addition as well.

### CODE REVIEW

**Comment by solverat** [comment]
jop this should be right.

**Comment by solverat** [comment]
🎉

**Comment by solverat** [comment]
btw, it would be great if you can trigger a new release so i can update my dependencies. thanks!

**Comment by cgsmith** [comment]
@solverat all set in `1.0.2`

**Pull request merged**
